### ISSUE TITLE
Getting 1R-MYBs and MYB-like sequences

### ISSUE THREAD

**Issue by cfz1998** [bpucker/MYB_annotator#3]
Hi! @bpucker

How could i get 1R-MYBs and MYB-like sequences using this pipeline? Do you have some advises? The 1R-MYBs and MYB-like sequences are very important to me.

Thank you for your reply!

--zcf

**Comment by bpucker** [comment]
Hi @cfz1998,
Thanks for your interest. You can use a customized collection of 1R-MYBs and MYB-like sequences as baits (--baits). You need to specify that they are the ingroup in another file (--info). The important question is probably how you would like to define an outgroup for 'MYB-like sequences'. That sounds like an undefined group to me. Anyways, you need also some outgroup sequences in both files to distinguish between sequences you would like to keep (ingroup) and those that you would like to exclude (outgroup) in the end. Please have a look at the two provided files MYB_baits.fasta and MYB_baits.txt to understand the required input file structure. Hope this helps!
Best wishes,
Boas

**Comment by cfz1998** [comment]
> 

Thank you! Boas.
You are a kind man.

Best wished,
--zcf
